# MonChat VectorDB (PostgreSQL + pgvector) 구성
# - 환경변수(.env) 기반으로 DB명/계정/포트 변경 가능

version: '3.8'
services:
  vectordb:
    # pgvector가 포함된 공식 이미지 사용
    image: pgvector/pgvector:pg16
    container_name: monchat-pgvector
    environment:
      # 기본값은 .env가 없을 때 사용됨
      POSTGRES_DB: ${VECTORDB_DB:-monchat}
      POSTGRES_USER: ${VECTORDB_USER:-monchat}
      POSTGRES_PASSWORD: ${VECTORDB_PASSWORD:-monchat}
    ports:
      # 호스트 포트는 환경변수 VECTORDB_PORT로 제어
      - "${VECTORDB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${VECTORDB_USER:-monchat}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # 데이터 영속화 볼륨
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata:
